// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAsleep: typeof import('~icons/carbon/asleep')['default']
    ICarbonAsleepFilled: typeof import('~icons/carbon/asleep-filled')['default']
    ICarbonEmail: typeof import('~icons/carbon/email')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
  }
}

export { }
